### ISSUE TITLE
Gazebo9 installation error

### ISSUE THREAD

**Issue by FooKii** [onlytailei/Gazebo_ROS_Pedestrians#12]
Hi guys,
 In case anyone using gazebo 9 you will have an error during compile about < no gzmath.hh > found.
 Just switch to gazebo 8 it will work.
And thanks for the package!

**Comment by ericzzj1989** [comment]
@FooKii Same problem. Have you solved it?

**Comment by FooKii** [comment]
yes, by switching to gazebo8
