### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by astronautas** [onlytailei/Gazebo_ROS_Pedestrians#2]
I followed all the instruction you provided on the main page of the repository. When I ran catkin_make in my workspace, I received such error:

* fatal error: data_collection/DataCollectionService.h: No such file or directory

as well as:

* fatal error: actor_services/SetPose.h: No such file or directory
compilation terminated.

Maybe this error could be the cause of the ones above?

Warnings   << turtlebot3_gazebo:cmake /home/lukas/catkin_ws/logs/turtlebot3_gazebo/build.cmake.001.log
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'gazebo' but neither 'gazebo_INCLUDE_DIRS' nor
  'gazebo_LIBRARIES' is defined.

Thank you!

**Comment by cj-oh** [comment]
Hi I've been facing with similar problem above during catkin build. 

Would you give me any suggestions? 

`fatal error: data_collection/DataCollectionServiceResponse.h: No such file or directory`

**Comment by limei0307** [comment]
I solved this problem by modifying the CMakeList file.

add_executable(data_collection_node src/main.cpp src/data_collection.cpp)
target_link_libraries(data_collection_node ${catkin_LIBRARIES})
add_dependencies(data_collection_node ${PROJECT_NAME}_generate_messages_cpp)

**Comment by aaravrav142** [comment]
How did you solved the `fatal error: actor_services/SetPose.h: No such file or directory` error?
Can you explain. Thanks.

**Comment by onlytailei** [comment]
@aaravrav142  That is actually ROS build dependency problem. Try to build through catkin build and install the service and node separately in CMakeList.
