### ISSUE TITLE
no rgb images in dataset

### ISSUE THREAD

**Issue by mohmdelsayed** [onlytailei/Gazebo_ROS_Pedestrians#4]
Hi Lei Tai,

Thank you for the good work and for providing your code to the public.  When I downloaded the dataset you provided in the read.me file, I found that no rgb information is available in the file.

In the read.me file:
The collected [pedestrian navigation dataset](https://ram-lab.com/file/tai_icra_2018_dataset.zip) contains:
- depth image
- RGB image
- target 
- social force classification
- social force
- sum force

However, I can only find the following: (no rgb data, checked by loading the files using pytorch)
- force_new.pth
- label_2_new.pth
- normalized_force_new.pth
- target_new.pth
- depth_float_new.pth

**Comment by onlytailei** [comment]
Thanks. I just updated it. Please check the new version through [google drive](https://drive.google.com/open?id=1H4U9Sl2M1E8Vp3ludJ1oPgu8a77qN3fX) or [our server](https://ram-lab.com/file/tai_icra_2018_dataset.zip)

**Comment by mohmdelsayed** [comment]
Thank you Lei for your prompt reply. I checked it and it's working fine. If you have the annotations (bounding boxes) for the pedestrians, can you please share them?

**Comment by onlytailei** [comment]
I'm sorry that they are not recorded in the original dataset. However, with the code in this repo, it should be very quick to set up such an environment and record the pedestrians' information.

**Comment by mohmdelsayed** [comment]
That is fine. I will explore the repo, thank you so much.

**Comment by hieuvmphan** [comment]
Hi all,
I might have a dumb question, but how can we load the .pth file
