### ISSUE TITLE
How to prohibit the pedestrians walk through the wall? 

### ISSUE THREAD

**Issue by scutDavid** [onlytailei/Gazebo_ROS_Pedestrians#6]
Hi, Tailei!
Firstly thanks for your wonderful job.
When I lauch the defult.launch with a maze.world, I find that the actor can walk through the wall of the maze and the laser cann't detect the body neither. The pedestrains are like the air.
So how could I  prohibit the pedestrians walk through the wall? 
Thanks for any suggestion!

**Comment by scutDavid** [comment]
Sorry.
Now I have found the answer.Just use the gpu_ray.so plugin to simulate the laser,not the cpu.

**Comment by onlytailei** [comment]
Good to know

**Comment by yani-rl-ai** [comment]
hi how did you change the gpu plugin to make detection using laser?
